version: '3'
services:
  pkappa2:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - pkappa2-data:/data
      - ./converters:/app/converters
    restart: unless-stopped
    environment:
      # Change values in .env file
      PKAPPA2_USER_PASSWORD: ${PKAPPA2_USER_PASSWORD}
      PKAPPA2_PCAP_PASSWORD: ${PKAPPA2_PCAP_PASSWORD}

volumes:
  pkappa2-data:
